travis:
  secure:
    BINSTAR_TOKEN: RTb7u/meQmYGICQQZqpHQ585RMQWLNGTTWfr3qdqkjKdjXvRVk5iD9ENuCaFECyzHY6K+WiJGBOs1OWNk7b9MMIkgJqQpcAB9d6IZRZhNu7twjNIjMWg6OADnZh/33h0xj3VHjw8wxRw9aiwr16LUdBscK5Iys3pOFjrtcw8It5B96e171L66nzwgF5n4lDW9RxoVDypxfU01Oo9XJQ8RiHnk5IK1qZ98dNceefd2FsprBisFTy8nBSPKJRcmeh5hL/H3aox5DsPiD4vwnosvsxiZ+Pmkikiap/TPpIYrEIJkgz4NbEzaXgE8gCzNCKOD8E7y5yA5T0b4QJsbwVocu1RknL5nk/aa81VMezPW6it83eH7h9pXxAA4waLo4cfGGLRv/0E7Ju/lWaK+fgOtfk6vLUxTL4wEpXXx8OLYi11Ay0sNk+bYMIRwitSxnTUAcQcb231eoIpZGNzf8DdrWKnKNxEXHaAntEWgFAoGYnLYHA7+ptZhUc7b5yeHOQY6IOwUB5rEmoHfn8xm0rnRLANtZkLykmr/3zIAjFIEwWf8yB7VxqU+9CAvzJelS5iQNVwmlnpMqQvUGDjOESPKqBRms6fbY7qSqf4Xn2nLcuv6cs2YJujW/BkJkHgsXI/eFWXFXkAbCHYe4+XF79wr4bTY8W3bxwQ7gQPCBEViVw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
