travis:
  secure:
    BINSTAR_TOKEN: UN5MQqtaPMhOCRlkMvfavd4m6hdxH7KkdgowEXlmfYr3lcs2Ah0XAesIv31OTcZEgFu72bdlhXj5mti28pBZszxIF8B2gr5E2qmja8VJdsV8DM+LXT3Zlp/fIewbriraHQbkY0kOgAK619BN8pyioASkguIz4UUdxWFGmO1L/GQF85r0AyuIt0uEV5yDn9XzVF0peo4asTqEUmPZAKpfsvlPg70U4Vg3nQWPk//+pHyOKevSAZUxyxYbrGW9v1sOXBWOYrRAfBYlys50P+p2zzHcPPZbbCi1pccgPvL7XUYyRzIlBfY8hvV8ggaL81+AZdo4PBxf6Axl2gAl00xdMAA/1D5TwGQ0BPrRx5NWE/g+mJ2JOzjJqn3FgnMF4HjGkg0tLs9AxU2RzdT6PxlcDp/xTYrlnjnUZExDaysZ8194KKX489cqajU9uJSlqBiIs/Y5lZacldu9W0onGevwJm4fG5zT6Pe/vla7dZDdWNV2dR644OfC8V0twxqyOuHLynML61kSbc0DHykcYJY0fjzWjGf+8xKxQn0iF8Li/5oO7yhVid3E5Cu/hAw+3ZS9g9VVm9CanY1rp6ACkE4FYAoj6egDSrQfXroN+Jw8WPPWRvkiVTmyn5dUKqLaPwX3hZwSER7Fp/gzD/Kj0lFA41PcczjOJqNEbXI4YofE2G4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
